#define MICROPY_HW_BOARD_NAME "Waveshare RP2040-PiZero"
#define MICROPY_HW_MCU_NAME "rp2040"

// #define MICROPY_HW_LED_STATUS (&pin_GPIO25)

#define DEFAULT_UART_BUS_RX (&pin_GPIO5)
#define DEFAULT_UART_BUS_TX (&pin_GPIO4)
